version: '3.8'

services:
  postgres:
    image: postgres:14
    restart: always
    container_name: pgdb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # comunicação entre serviços
      - "15672:15672" # painel web
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  payment-service:
    build: ./payment-service
    container_name: payment-service
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - rabbitmq

  notification-service:
    build: ./notification-service
    container_name: notification-service
    restart: always
    ports:
      - "3002:3002"
    depends_on:
      - rabbitmq

volumes:
  pgdata: